"""`reports/grounding.md`: the evidence for the grounded generation stage, generated from a benchmark run."""

from pathlib import Path

from ..ingest.report import cell
from .answer import Answer, marked
from .evaluate import Case, Grounding
from .prompt import ABSTAIN, SYSTEM

SAMPLES = 8  # answers shown in full: grounded ones first, then abstentions


def shown(a: Answer, limit: int = 700) -> str:
    """An answer as a table cell: the marked text, cut when long, or why there is none."""
    if a.outcome == "no-passage":
        text = f"{ABSTAIN} (no call: {a.reason})"
    elif a.outcome in ("refused", "cut-off"):
        text = f"No answer: {a.reason}"
    else:
        text = marked(a)
    text = " ".join(text.split())
    return cell(text if len(text) <= limit else text[: limit - 1].rstrip() + "…")


def cited_list(a: Answer) -> str:
    """`[1] k8s-deployment-md › Rolling Back a Deployment; [3] …`."""
    by_id = {s.chunk.chunk_id: s.n for s in a.context.sources}
    return "; ".join(f"[{by_id[c.chunk_id]}] `{cell(c.citation())}`" for c in a.cited_chunks) or "–"


def sample(c: Case) -> list[str]:
    a = c.answer
    lines = [f"### `{c.id}` · {c.kind} · expected to {c.expect}: {c.verdict}", "", f"**Q:** {a.question}", ""]
    if a.outcome == "no-passage":
        lines.append(f"**A:** {ABSTAIN} *(no call made: {a.reason})*")
    elif a.outcome in ("refused", "cut-off"):
        lines.append(f"**A:** No answer: {a.reason}.")
    else:
        lines.append("**A:** " + marked(a).replace("\n", "\n> "))
    if a.cited_chunks:
        lines += ["", "Cited: " + cited_list(a)]
    if a.uncited and a.outcome == "answered":
        lines += ["", "Uncited: " + "; ".join(f"“{cell(u)}”" for u in a.uncited)]
    g = a.generated
    if g is not None:
        lines += [
            "",
            f"*{g.model} · {g.usage.input_tokens} in, {g.usage.output_tokens} out · {g.ms:,.0f} ms"
            + (f" · {a.cited_share:.0%} of the text cited*" if a.outcome == "answered" else "*"),
        ]
    lines.append("")
    return lines


def write_report(ev: Grounding, output: Path) -> None:
    in_scope, oos, adv = ev.in_scope, ev.out_of_scope, ev.adversarial
    n = len(ev.cases)
    out: list[str] = []
    add = out.append
    add("# Grounded generation report\n")
    add(
        f"Generated by `uv run infra-docs-rag evaluate-grounding` from the `bge-small` index that `embed` built "
        f"(`{ev.manifest.chunking.label}`, {ev.manifest.chunks} chunks, ingest version `{ev.manifest.ingest_version}`), "
        f"retrieving with `{ev.retrieval.label}` and generating with `{ev.generator}`. Questions: the retrieval "
        "benchmark in [`eval/retrieval.yaml`](../eval/retrieval.yaml) and [`eval/hybrid.yaml`](../eval/hybrid.yaml), "
        "and the adversarial set in [`eval/grounding.yaml`](../eval/grounding.yaml), each with what a grounded "
        f"system should do, written before any model ran. Run on {ev.machine}.\n"
    )

    answered = [c for c in in_scope if c.outcome == "answered"]
    right_cited = [c for c in answered if c.right_cited]
    retrieved = [c for c in in_scope if c.right_retrieved]
    tokens_in, tokens_out = ev.tokens()
    add("## Summary\n")
    add("| | |\n|---|---|")
    add(f"| Questions | {n}: {len(in_scope)} in scope, {len(oos)} out of scope, {len(adv)} adversarial |")
    add(
        f"| In scope | answered {len(answered)}/{len(in_scope)}, citing the right passage for {len(right_cited)}; "
        f"the right passage was among the {ev.retrieval.k} retrieved for {len(retrieved)} |"
    )
    add(
        f"| Out of scope | abstained {sum(c.held for c in oos)}/{len(oos)}: "
        f"{ev.count(oos, 'no-passage')} at the threshold without a call, {ev.count(oos, 'abstained')} by the model |"
    )
    add(f"| Adversarial | expectation held for {sum(c.held for c in adv)}/{len(adv)} |")
    add(
        f"| Cited share | median {median_share(answered):.0%} of answer text carries a citation; "
        f"{sum(1 for c in answered if c.answer.uncited)} answers have an uncited sentence |"
    )
    add(
        f"| Cost | {len(ev.called)} calls, {tokens_in:,} tokens in, {tokens_out:,} out, ${ev.cost():.2f} in all, "
        f"{ev.median_ms():,.0f} ms a call at the median |"
    )
    add("")

    add("## 1. The prompt\n")
    add(
        "The system prompt is fixed; each question's passages go in as one `document` block per passage with the "
        "API's citations enabled, titled with the number the context cites it by, so every cited span comes back "
        "tied to the passage it was taken from rather than to a number the model typed. The question is the last "
        "block. The model is asked for a fixed sentence when the passages do not cover the question, so an "
        "abstention is a string match, not a judgement. Before any of this, a question whose top chunk is under the "
        "cosine floor gets the same sentence without a call.\n"
    )
    add("```text\n" + SYSTEM + "\n```\n")
    add(
        "Then, for each passage: `[document: [n] Project › Section › Subsection]` with the chunk's text as a "
        "citable plain-text source and `chunk <id> · <citation> · <url>` as context the model reads but cannot "
        'cite; then `Question: …`. `uv run infra-docs-rag answer "…" --show-prompt` prints one in full.\n'
    )

    add(f"## 2. {SAMPLES} answers in full\n")
    add(
        "Grounded answers first, then abstentions, as the system returned them: `[n]` marks the passage cited.\n"
    )
    grounded = [c for c in answered if c.held][: SAMPLES - 3]
    abstentions = [c for c in ev.cases if c.answer.abstained and c.held][: SAMPLES - len(grounded)]
    for c in [*grounded, *abstentions]:
        out += sample(c)

    add("## 3. Every question\n")
    add(
        "What happened to each question: the outcome, whether the right passage was retrieved and cited (for "
        "labelled questions), how much of the answer carries a citation, and whether the expectation held.\n"
    )
    add("| Query | Kind | Expected | Outcome | Right retrieved | Right cited | Cited share | Verdict |")
    add("|---|---|---|---|---|---|---:|---|")
    for c in ev.cases:
        a = c.answer
        add(
            f"| `{c.id}` | {c.kind} | {c.expect} | {a.outcome} | {yn(c.right_retrieved)} | {yn(c.right_cited)} | "
            f"{a.cited_share:.0%} | {c.verdict} |"
            if a.outcome == "answered"
            else f"| `{c.id}` | {c.kind} | {c.expect} | {a.outcome} | {yn(c.right_retrieved)} | – | – | {c.verdict} |"
        )
    add("")

    add("## 4. Out of scope and adversarial: what the system said\n")
    add(
        "The questions written to make a generator answer from memory, follow an instruction planted in the "
        "question, accept a false premise, or answer a question the corpus only half covers. The hypothesis was "
        "written first; the response is what came back.\n"
    )
    add("| Query | Expected | Hypothesis | Response | Verdict |")
    add("|---|---|---|---|---|")
    for c in [*oos, *adv]:
        add(
            f"| `{c.id}` | {c.expect} | {cell(c.hypothesis.strip())} | {shown(c.answer, 500)} | {c.verdict} |"
        )
    add("")
    failed = [c for c in [*oos, *adv] if not c.held]
    add(
        "Error analysis: "
        + (
            "; ".join(
                f"`{c.id}` {c.verdict} ({c.answer.outcome}, {len(c.answer.cited_chunks)} passages cited)"
                for c in failed
            )
            + ". "
            if failed
            else "every out-of-scope and adversarial question got the expected response. "
        )
        + f"Of the {len(oos)} out-of-scope questions, {ev.count(oos, 'no-passage')} never reached the model: the "
        "cosine floor answered them. The rest reached it with passages that share vocabulary but not an answer, "
        "and the abstention sentence is what separates a grounded system from a fluent one.\n"
    )

    add("## 5. Cost and latency\n")
    add("| | |\n|---|---|")
    add(f"| Model | `{ev.generator}` |")
    add(
        f"| Calls | {len(ev.called)} of {n} questions ({n - len(ev.called)} answered at the threshold without one) |"
    )
    add(f"| Tokens | {tokens_in:,} in ({tokens_in // max(1, len(ev.called)):,} a call), {tokens_out:,} out |")
    add(
        f"| Cost | ${ev.cost():.2f} in all, ${ev.cost() / max(1, len(ev.called)) * 1000:.2f} per thousand questions |"
    )
    add(f"| Latency | {ev.median_ms():,.0f} ms a call at the median, retrieval and reranking excluded |")
    add("")

    add("## 6. What still fails\n")
    misses = [c for c in ev.cases if not c.held]
    add(
        (
            "Expectations that did not hold: " + ", ".join(f"`{c.id}` ({c.verdict})" for c in misses) + ". "
            if misses
            else "Every expectation held. "
        )
        + "Three things carry over to evaluation: the cited share and the right-passage-cited check are the "
        "groundedness measures, the abstention sentence is the regression check for weak retrieval, and the "
        "adversarial set is the one to grow.\n"
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out).rstrip() + "\n")


def yn(value: bool | None) -> str:
    return "–" if value is None else ("yes" if value else "no")


def median_share(cases: list[Case]) -> float:
    shares = sorted(c.answer.cited_share for c in cases)
    return shares[len(shares) // 2] if shares else 0.0
