"""`reports/ingestion.md`: the evidence that ingestion works, generated from the records."""

import json
import re
from collections import Counter
from pathlib import Path

from .dedup import NEAR_DUPLICATE, SHINGLE_WORDS
from .models import Document, ParseStatus
from .sources import Source

SAMPLE_SOURCES = [
    "k8s-configmap",
    "prom-alerting-rules-md",
    "argocd-cm-yaml",
    "cncf-security-whitepaper",
    "fixture-scanned-pdf",
]
CLEANING_RULES = {
    "html": "main-content extraction drops navigation, sidebars, version pickers, feedback widgets and footers",
    "markdown": "front matter becomes the title; Hugo shortcodes, HTML comments, images and link targets are removed",
    "text": "Unicode and whitespace normalization only; indentation is kept",
    "pdf": "repeated headers and footers, page numbers and footnote markers are removed; wrapped lines and soft-hyphenated words are rejoined",
}


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def excerpt(text: str, limit: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def removed_lines(doc: Document, limit: int = 6) -> list[str]:
    """Raw lines that did not survive into the cleaned text, in document order."""
    kept = " ".join(doc.cleaned_text.split())
    removed: list[str] = []
    for line in doc.raw_text.split("\n"):
        line = " ".join(line.replace("\u00ad", "").split()).rstrip("-")
        if line and line not in kept and line not in removed:
            removed.append(line)
            if len(removed) == limit:
                break
    return removed


def compact_json(record: dict) -> str:
    """Pretty JSON with one line per list item, so section and page lists stay short."""
    lines = []
    for key, value in record.items():
        if isinstance(value, list) and value:
            items = ",\n".join("    " + json.dumps(item, ensure_ascii=False) for item in value)
            lines.append(f'  "{key}": [\n{items}\n  ]')
        else:
            dumped = json.dumps(value, indent=2, ensure_ascii=False).replace("\n", "\n  ")
            lines.append(f'  "{key}": {dumped}')
    return "{\n" + ",\n".join(lines) + "\n}"


def section_path(doc: Document, offset: int) -> str:
    page, section = doc.locate(offset)
    where = [f"page {page.number} ({page.method})"] if page else []
    where.append("section " + " › ".join(section.path) if section else "before the first heading")
    return ", ".join(where)


def write_report(docs: list[Document], sources: list[Source], pairs_file: Path, output: Path) -> None:
    by_id = {d.document_id: d for d in docs}
    notes = {s.id: s.note for s in sources}
    pairs = json.loads(pairs_file.read_text()) if pairs_file.exists() else []
    real = [d for d in docs if not d.source_id.startswith("fixture-")]
    statuses = Counter(d.parse_status.value for d in docs)
    types = Counter(d.source_type.value for d in docs)
    duplicates = [d for d in docs if d.duplicate]
    version = docs[0].provenance.ingest_version if docs else "?"

    out: list[str] = []
    add = out.append
    add("# Ingestion report\n")
    add(
        "Generated by `uv run infra-docs-rag report` from `data/processed/documents.jsonl` "
        f"(ingest version `{version}`). Rebuild everything with `uv run infra-docs-rag all`.\n"
    )

    add("## Summary\n")
    add("| | |\n|---|---|")
    add(f"| Sources | {len(docs)}: " + " · ".join(f"{n} {t}" for t, n in types.most_common()) + " |")
    add("| Parse status | " + " · ".join(f"{s} {n}" for s, n in statuses.most_common()) + " |")
    kinds = Counter(d.duplicate.kind for d in duplicates)
    add(
        f"| Duplicates | {kinds['exact']} exact · {kinds['near']} near (Jaccard ≥ {NEAR_DUPLICATE} over {SHINGLE_WORDS}-word shingles) |"
    )
    raw_chars = sum(len(d.raw_text) for d in real)
    clean_chars = sum(len(d.cleaned_text) for d in real if not d.duplicate)
    add(f"| Text | {raw_chars:,} raw characters → {clean_chars:,} cleaned and unique |\n")

    add("## Documents\n")
    add("| Source | Type | Title | Status | Raw → cleaned chars | Sections | Pages | Duplicate of |")
    add("|---|---|---|---|---|---|---|---|")
    for d in docs:
        dup = (
            f"{by_id[d.duplicate.of].source_id} ({d.duplicate.kind}, {d.duplicate.similarity:.2f})"
            if d.duplicate
            else ""
        )
        add(
            f"| `{d.source_id}` | {d.source_type.value} | {cell(excerpt(d.title or '', 48))} | {d.parse_status.value} "
            f"| {len(d.raw_text):,} → {len(d.cleaned_text):,} | {len(d.sections)} | {len(d.pages) or ''} | {dup} |"
        )
    add("")

    add("## Cleaning, before and after\n")
    add(
        "*Raw* is what a naive extractor would index: every visible string on the page, or the file as "
        "downloaded. *Cleaned* is what the pipeline keeps. The removed lines are the first few raw lines "
        "that did not survive into the cleaned text.\n"
    )
    for d in real:
        if d.parse_status not in (ParseStatus.OK, ParseStatus.OCR_FALLBACK):
            continue
        share = 1 - len(d.cleaned_text) / len(d.raw_text) if d.raw_text else 0
        add(f"### `{d.source_id}`: {d.title}\n")
        add(f"- {len(d.raw_text):,} → {len(d.cleaned_text):,} characters ({share:.0%} removed)")
        add(f"- Rules: {CLEANING_RULES[d.source_type.value]}")
        if d.sections:
            add(
                f"- Structure kept: {len(d.sections)} sections"
                + (f" across {len(d.pages)} pages" if d.pages else "")
            )
        removed = removed_lines(d)
        if removed:
            add(
                "- Removed, for example: "
                + " · ".join(f"`{excerpt(r, 50).replace('`', '')}`" for r in removed)
            )
        if d.duplicate:
            add(f"- Flagged as a {d.duplicate.kind} duplicate of `{by_id[d.duplicate.of].source_id}`")
        add("\n<details><summary>First 300 characters, before and after</summary>\n")
        add("Before:\n\n```text\n" + excerpt(d.raw_text, 300) + "\n```\n")
        add("After:\n\n```text\n" + excerpt(d.cleaned_text, 300) + "\n```\n</details>\n")

    add("## Duplicates\n")
    add(
        f"Exact duplicates share a content hash (SHA-256 of the cleaned text, lowercased, whitespace "
        f"collapsed). Near duplicates are scored by Jaccard similarity over {SHINGLE_WORDS}-word shingles; "
        f"at {NEAR_DUPLICATE} or above, the later document is flagged and the first one seen is kept.\n"
    )
    add("| Flagged | Kept | Kind | Similarity | Why they match |")
    add("|---|---|---|---|---|")
    for d in duplicates:
        add(
            f"| `{d.source_id}` | `{by_id[d.duplicate.of].source_id}` | {d.duplicate.kind} "
            f"| {d.duplicate.similarity:.3f} | {cell(notes.get(d.source_id) or '')} |"
        )
    add("\nThe closest pairs that were compared, to show the margin around the threshold:\n")
    add("| Pair | Jaccard | Verdict |")
    add("|---|---|---|")
    for pair in sorted(pairs, key=lambda p: p["similarity"], reverse=True)[:8]:
        a, b = by_id[pair["kept"]], by_id[pair["other"]]
        verdict = "duplicate" if pair["similarity"] >= NEAR_DUPLICATE else "distinct"
        add(f"| `{a.source_id}` ↔ `{b.source_id}` | {pair['similarity']:.3f} | {verdict} |")
    add("")

    add("## Provenance\n")
    add(
        "Every record carries where it came from and what produced it. Sections and pages are "
        "character spans of `cleaned_text`, so any chunk cut from it can be traced back to its "
        "source file, page, section and ingestion version.\n"
    )
    for source_id in SAMPLE_SOURCES:
        d = next((d for d in docs if d.source_id == source_id), None)
        if not d:
            continue
        record = d.model_dump(mode="json", exclude={"raw_text"})
        record["cleaned_text"] = excerpt(d.cleaned_text, 160)
        for key in ("sections", "pages"):
            if len(record[key]) > 3:
                record[key] = record[key][:3] + [f"… {len(record[key]) - 3} more"]
        add(f"### `{d.source_id}`\n")
        add("```json\n" + compact_json(record) + "\n```\n")
        if d.cleaned_text:
            middle = len(d.cleaned_text) // 2
            offset = d.cleaned_text.find(" ", middle) + 1 or middle  # start on a word
            chunk = excerpt(d.cleaned_text[offset : offset + 160], 120)
            add(
                f'A chunk from the middle, *"{chunk}"*, traces to {section_path(d, offset)} of '
                f"`{d.provenance.local_path}` (SHA-256 `{d.provenance.source_sha256[:12]}…`), "
                f"ingest version `{d.provenance.ingest_version}`.\n"
            )

    add("## Parse failures and fallbacks\n")
    add("Every file that did not parse cleanly, what is wrong with it, and what the pipeline did.\n")
    add("| Source | What is wrong with it | Status | What happened |")
    add("|---|---|---|---|")
    for d in docs:
        if d.parse_status == ParseStatus.OK and not d.parse_error:
            continue
        if d.parse_status == ParseStatus.OCR_FALLBACK:
            ocr_pages = [p.number for p in d.pages if p.method == "ocr"]
            happened = f'OCR read page(s) {", ".join(map(str, ocr_pages))}: "{excerpt(d.cleaned_text, 70)}"'
        else:
            happened = d.parse_error or ""
        add(
            f"| `{d.source_id}` | {cell(notes.get(d.source_id) or '')} | {d.parse_status.value} | {cell(happened)} |"
        )
    add("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(re.sub(r"\n{3,}", "\n\n", "\n".join(out)))
