"""`reports/hybrid-search.md`: the evidence for the hybrid search stage, generated from a comparison."""

import statistics
from pathlib import Path

from ..chunk.evaluate import K
from ..chunk.report import rank
from ..embed.index import Hit
from ..ingest.report import cell
from .compare import Comparison, Run, name
from .evaluate import KINDS
from .fusion import HybridHit
from .report import answered_by_label
from .retriever import DEFAULT_RETRIEVAL


def components(hit: Hit | None) -> str:
    """`0.62 (#3) · bm25 7.1 (#1)` for a hybrid hit, the plain score otherwise, `–` for nothing."""
    if hit is None:
        return "–"
    if isinstance(hit, HybridHit):
        lexical = f"bm25 {hit.lexical:.1f} (#{hit.lexical_rank})" if hit.lexical_rank else "bm25 0"
        return f"cos {hit.dense:.2f} (#{hit.dense_rank}) · {lexical}"
    return f"{hit.score:.2f}"


def silent(run: Run, query_id: str, floor: float | None) -> bool:
    """Whether the configuration would show nothing for the query under the default threshold: no hit at
    all (BM25 with no shared term), or a top cosine score under the floor."""
    outcome = run.outcomes[query_id]
    if outcome.top is None:
        return True
    if run.retrieval.mode == "lexical":
        return False  # BM25 has no floor; anything it ranks, it shows
    return floor is not None and outcome.top_gate is not None and outcome.top_gate < floor


def write_report(cmp: Comparison, output: Path) -> None:
    in_scope, oos = cmp.in_scope, cmp.out_of_scope
    n = len(in_scope)
    floor = DEFAULT_RETRIEVAL.min_score
    dense, lexical, best = cmp.dense, cmp.lexical, cmp.best_hybrid()
    loses = cmp.dense_loses()
    extra = set(cmp.extra)

    out: list[str] = []
    add = out.append
    add("# Hybrid search report\n")
    add(
        "Generated by `uv run infra-docs-rag evaluate-hybrid` from the `bge-small` index that `embed` built "
        f"(`{cmp.manifest.chunking.label}`, {cmp.manifest.chunks} chunks, ingest version "
        f"`{cmp.manifest.ingest_version}`), a BM25 index over the same chunks ({cmp.lexical_terms:,} terms), "
        "the labelled queries in [`eval/retrieval.yaml`](../eval/retrieval.yaml) and this stage's own in "
        f"[`eval/hybrid.yaml`](../eval/hybrid.yaml). Run on {cmp.machine}.\n"
    )

    add("## Summary\n")
    add("| | |\n|---|---|")
    add(
        f"| Queries | {len(cmp.queries)}: {n} in scope, {len(oos)} out of scope; {len(extra)} written for this stage |"
    )
    add(
        f"| Dense | right chunk first for {dense.hits(1, in_scope)}/{n}, in the top {K} for {dense.hits(K, in_scope)}/{n}, "
        f"MRR {dense.mrr(in_scope):.2f} |"
    )
    add(
        f"| Lexical (BM25) | first for {lexical.hits(1, in_scope)}/{n}, top {K} for {lexical.hits(K, in_scope)}/{n}, "
        f"MRR {lexical.mrr(in_scope):.2f} |"
    )
    add(
        f"| Best fusion | `{name(best.retrieval)}`: first for {best.hits(1, in_scope)}/{n}, top {K} for "
        f"{best.hits(K, in_scope)}/{n}, MRR {best.mrr(in_scope):.2f} |"
    )
    add(f"| Dense loses | {len(loses)} queries where BM25 ranks the right chunk higher than cosine does |")
    add(
        f"| Silence | out-of-scope questions left with nothing: dense {sum(silent(dense, q.id, floor) for q in oos)}/{len(oos)} "
        f"(cosine under {floor:.2f}), BM25 {sum(silent(lexical, q.id, None) for q in oos)}/{len(oos)} (no shared term) |"
    )
    add("")

    add("## 1. Configurations\n")
    add(
        f"One full ranking per question per configuration. *First* and *top {K}* count the in-scope questions "
        f"whose first right chunk ranks there; the kind columns count the top {K} within each kind.\n"
    )
    kinds = [k for k in KINDS if k != "out-of-scope"]
    add(
        "| Configuration | First | Top "
        + str(K)
        + " | MRR | "
        + " | ".join(f"{k} ({len(cmp.of_kind(k))})" for k in kinds)
        + " |"
    )
    add("|---|---:|---:|---:|" + "---:|" * len(kinds))
    for run in cmp.runs:
        row = f"| `{name(run.retrieval)}` | {run.hits(1, in_scope)}/{n} | {run.hits(K, in_scope)}/{n} | {run.mrr(in_scope):.2f} | "
        add(row + " | ".join(str(run.hits(K, cmp.of_kind(k))) for k in kinds) + " |")
    add("")

    add("## 2. Where dense retrieval loses\n")
    if loses:
        add(
            f"{len(loses)} in-scope questions rank higher under BM25 than under cosine. The hybrid columns show "
            "whether fusion keeps the gain.\n"
        )
        add(
            "| Query | Kind | Question | Dense | BM25 | "
            + " | ".join(f"`{name(r.retrieval)}`" for r in cmp.hybrids)
            + " |"
        )
        add("|---|---|---|---:|---:|" + "---:|" * len(cmp.hybrids))
        for q in loses:
            mark = " ★" if q.id in extra else ""
            add(
                f"| `{q.id}`{mark} | {q.kind} | {cell(q.text)} | {rank(dense.rank(q.id))} | {rank(lexical.rank(q.id))} | "
                + " | ".join(rank(r.rank(q.id)) for r in cmp.hybrids)
                + " |"
            )
        add("\n★ written for this stage.\n")
    else:
        add(
            "No in-scope question ranks higher under BM25 than under cosine yet. `eval/hybrid.yaml` is where the ones that should go.\n"
        )

    add("## 3. Every question, every configuration\n")
    add(
        "Rank of the first right chunk; `–` when no chunk answers (for BM25, often because the question shares no term with it).\n"
    )
    add("| Query | Kind | Answered by | " + " | ".join(f"`{name(r.retrieval)}`" for r in cmp.runs) + " |")
    add("|---|---|---|" + "---:|" * len(cmp.runs))
    for q in in_scope:
        mark = " ★" if q.id in extra else ""
        add(
            f"| `{q.id}`{mark} | {q.kind} | {answered_by_label(cmp.answers[q.id], q)} | "
            + " | ".join(rank(r.rank(q.id)) for r in cmp.runs)
            + " |"
        )
    add("")

    add("## 4. Out of scope: what each side says\n")
    add(
        f"The retrieval stage's floor is cosine {floor:.2f}, which the corpus' own near-miss questions clear. BM25 "
        "scores a question at 0 when it shares no term with any chunk, and low when it shares only common ones. "
        "In-scope questions are the reference: the top BM25 score the right answers reach.\n"
    )
    tops = [lexical.outcomes[q.id].top.score for q in in_scope if lexical.outcomes[q.id].top is not None]
    if tops:
        add(
            f"In scope, the top BM25 score is {statistics.median(tops):.1f} at the median and {min(tops):.1f} at the "
            f"lowest, over the {len(tops)} questions BM25 ranks at all.\n"
        )
    add(
        "| Question | Top cosine chunk | Cosine | Top BM25 chunk | BM25 | `"
        + name(best.retrieval)
        + "` top |"
    )
    add("|---|---|---:|---|---:|---|")
    for q in oos:
        d, lex, h = dense.outcomes[q.id].top, lexical.outcomes[q.id].top, best.outcomes[q.id].top
        add(
            f"| {cell(q.text)} | `{d.chunk.citation()}` | {d.score:.2f} | "
            + (f"`{lex.chunk.citation()}` | {lex.score:.1f}" if lex is not None else "nothing | 0")
            + f" | {components(h)} |"
        )
    add("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out).rstrip() + "\n")
