"""`reports/reranking.md`: the evidence for the reranking stage, generated from a comparison."""

import statistics
from pathlib import Path

from ..chunk.evaluate import K
from ..chunk.report import rank
from ..embed.index import Hit
from ..ingest.report import cell
from .evaluate import KINDS
from .rerank_compare import LATENCY_BUDGET_MS, RerankComparison, Run, name, top_gate
from .retriever import DEFAULT_RETRIEVAL

RELEVANCE_GRID = (0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9)


def short(hit: Hit) -> str:
    """A chunk's section, with its source when the section alone would not say: `Immutable ConfigMaps`."""
    c = hit.chunk
    return cell(c.section if c.section_path else c.source_id)


def order(hits: list[Hit], right: Hit | None) -> str:
    """The top K as section names, the right one marked: `Pending ✓ › Waiting › Crashing`."""
    return " › ".join(
        short(h) + (" ✓" if right is not None and h.chunk.chunk_id == right.chunk.chunk_id else "")
        for h in hits
    )


def worse(a: int | None, b: int | None) -> bool:
    """Whether rank `a` is worse than rank `b`; no rank at all is the worst."""
    return b is not None and (a is None or a > b)


def ms(value: float) -> str:
    return f"{value:,.0f} ms" if value >= 10 else f"{value:.1f} ms"


def write_report(cmp: RerankComparison, output: Path) -> None:
    in_scope, oos = cmp.in_scope, cmp.out_of_scope
    n = len(in_scope)
    first, best, pick = cmp.first, cmp.best(), cmp.pick()
    floor = DEFAULT_RETRIEVAL.min_score
    kinds = [k for k in KINDS if k != "out-of-scope"]
    budget = f"{LATENCY_BUDGET_MS / 1000:.0f} s"

    out: list[str] = []
    add = out.append
    add("# Reranking report\n")
    rerankers = [r for r in cmp.reranked if r.reranker is not None]
    models = {r.reranker.name: r.reranker for r in rerankers if r.reranker}
    add(
        "Generated by `uv run infra-docs-rag evaluate-rerank` from the `bge-small` index that `embed` built "
        f"(`{cmp.manifest.chunking.label}`, {cmp.manifest.chunks} chunks, ingest version "
        f"`{cmp.manifest.ingest_version}`), the labelled queries in [`eval/retrieval.yaml`](../eval/retrieval.yaml) "
        "and [`eval/hybrid.yaml`](../eval/hybrid.yaml), and the expectations in "
        f"[`eval/rerank.yaml`](../eval/rerank.yaml). The first stage is `{first.retrieval.label}`, the hybrid "
        "search report's pick. "
        + " ".join(f"`{m.name}` is `{m.model_id}` at `{m.revision[:7]}`: {m.note}" for m in models.values())
        + f" Run on {cmp.machine}.\n"
    )

    changed = cmp.changed_set(pick)
    moved = [q for q in in_scope if first.rank(q.id) != pick.rank(q.id)]
    up = [q for q in moved if worse(first.rank(q.id), pick.rank(q.id))]
    down = [q for q in moved if worse(pick.rank(q.id), first.rank(q.id))]
    cosine_silent = sum(
        top_gate(first.outcomes[q.id]) is not None and top_gate(first.outcomes[q.id]) < floor for q in oos
    )
    add("## Summary\n")
    add("| | |\n|---|---|")
    add(f"| Queries | {len(cmp.queries)}: {n} in scope, {len(oos)} out of scope |")
    add(
        f"| First stage | right chunk first for {first.hits(1, in_scope)}/{n}, in the top {K} for "
        f"{first.hits(K, in_scope)}/{n}, MRR {first.mrr(in_scope):.2f}, {ms(first.median('ms', in_scope))} a question |"
    )
    add(
        f"| Best rerank | `{name(best.retrieval)}`: first for {best.hits(1, in_scope)}/{n}, top {K} for "
        f"{best.hits(K, in_scope)}/{n}, MRR {best.mrr(in_scope):.2f}, {ms(best.median('ms', in_scope))} a question |"
    )
    add(
        f"| Pick | `{name(pick.retrieval)}`, the best under {budget} a question: first for "
        f"{pick.hits(1, in_scope)}/{n}, top {K} for {pick.hits(K, in_scope)}/{n}, MRR {pick.mrr(in_scope):.2f}, "
        f"{ms(pick.median('ms', in_scope))} a question |"
    )
    add(
        f"| Context changes | under the pick, the top {K} a generator reads holds different chunks for "
        f"{len(changed)}/{n} questions, and the right chunk's rank changes for {len(moved)}: up for {len(up)}, "
        f"down for {len(down)} |"
    )
    add(
        f"| Silence | the cosine floor leaves {cosine_silent}/{len(oos)} out-of-scope questions with nothing, "
        "before and after; section 4 is what the reranker's own score would add |"
    )
    add("")

    add("## 1. Configurations\n")
    add(
        f"One ranking per question per configuration, from the same first stage. *First* and *top {K}* count the "
        f"in-scope questions whose first right chunk ranks there; a reranked configuration can only rank what the "
        f"first stage handed it, so a right chunk past its candidates counts as not found. Times are medians over "
        "the in-scope questions, embedding the question excluded.\n"
    )
    add(
        "| Configuration | First | Top "
        + str(K)
        + " | MRR | "
        + " | ".join(f"{k} ({len(cmp.of_kind(k))})" for k in kinds)
        + " | Pairs | First stage | Rerank | Total |"
    )
    add("|---|---:|---:|---:|" + "---:|" * len(kinds) + "---:|---:|---:|---:|")
    for run in cmp.runs:
        row = (
            f"| `{name(run.retrieval)}` | {run.hits(1, in_scope)}/{n} | {run.hits(K, in_scope)}/{n} | "
            f"{run.mrr(in_scope):.2f} | "
        )
        row += " | ".join(str(run.hits(K, cmp.of_kind(k))) for k in kinds)
        row += (
            f" | {run.outcomes[in_scope[0].id].scored or '–'} | {ms(run.median('first_ms', in_scope))} | "
            f"{ms(run.median('rerank_ms', in_scope)) if run.reranker else '–'} | {ms(run.median('ms', in_scope))} |"
        )
        add(row)
    add("")

    add(f"## 2. Where reranking changes the context: `{name(pick.retrieval)}`\n")
    add(
        f"The top {K} is what a generator reads. Reranking reorders it for nearly every question, mostly below "
        f"the right chunk, and swaps at least one chunk in it for {len(changed)} of the {n}. These are the "
        f"questions where the right chunk's own rank changes, with the top {K} before and after as section "
        f"names, the right chunk marked ✓: {len(up)} move up, {len(down)} move down.\n"
    )
    if moved:
        add("| Query | Kind | Before | After | Rank |")
        add("|---|---|---|---|---:|")
        for q in moved:
            a, b = first.outcomes[q.id], pick.outcomes[q.id]
            add(
                f"| `{q.id}` | {q.kind} | {order(a.top, a.right)} | {order(b.top, b.right)} | "
                f"{rank(a.rank)} → {rank(b.rank)} |"
            )
    else:
        add("No in-scope question's right chunk moved.")
    add("")

    add("## 3. Latency and cost\n")
    add(
        "The first stage scores every chunk against the question once, cheaply: a dot product per chunk and a "
        "BM25 lookup per term. A cross-encoder runs the question and one chunk through the whole model per pair, "
        "so its cost is pairs × a forward pass. Per question, on this machine:\n"
    )
    add(
        "| Configuration | Parameters | Pairs | ms per pair | Rerank median | Rerank p95 | Total median | "
        "× first stage | First | MRR |"
    )
    add("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    base = first.median("ms", in_scope)
    for run in cmp.runs:
        if run.reranker is None:
            add(
                f"| `first stage` | – | – | – | – | – | {ms(base)} | 1× | {run.hits(1, in_scope)}/{n} | "
                f"{run.mrr(in_scope):.2f} |"
            )
            continue
        pairs = run.outcomes[in_scope[0].id].scored
        per_pair = run.median("rerank_ms", in_scope) / pairs if pairs else 0.0
        add(
            f"| `{name(run.retrieval)}` | {parameters(cmp, run)} | {pairs} | {per_pair:.1f} | "
            f"{ms(run.median('rerank_ms', in_scope))} | {ms(run.p95('rerank_ms', in_scope))} | "
            f"{ms(run.median('ms', in_scope))} | {run.median('ms', in_scope) / base:,.0f}× | "
            f"{run.hits(1, in_scope)}/{n} | {run.mrr(in_scope):.2f} |"
        )
    add("")
    if rerankers:
        cheapest = min(rerankers, key=lambda r: r.median("ms", in_scope))
        slowest = max(rerankers, key=lambda r: r.median("ms", in_scope))
        add(
            f"The first stage takes {ms(base)}; the cheapest rerank, `{name(cheapest.retrieval)}`, "
            f"{ms(cheapest.median('ms', in_scope))}, and the most expensive, `{name(slowest.retrieval)}`, "
            f"{ms(slowest.median('ms', in_scope))}, "
            f"{slowest.median('ms', in_scope) / cheapest.median('ms', in_scope):.0f}× as much. The cost is per "
            "pair and the same whether the order changes or not, so what buys the gain is the depth: candidates "
            "the first stage ranked low but right. The step is worth it when the generator reads only the top few "
            "passages and the first stage has the answer among its candidates but not at the top, and it can do "
            "nothing for a question whose answer the first stage never hands it. The pick, "
            f"`{name(pick.retrieval)}`, is the best configuration under {budget} a question, the time someone "
            "waits for an answer before the generator has even started"
            + (
                f"; `{name(best.retrieval)}` answers {best.hits(1, in_scope) - pick.hits(1, in_scope)} more first "
                f"at {best.median('ms', in_scope) / pick.median('ms', in_scope):.1f}× the time.\n"
                if best is not pick
                else ".\n"
            )
        )

    add("## 4. Relevance as a signal\n")
    add(
        "The cosine floor reads the first stage. A cross-encoder's relevance is a second score, in [0, 1] after a "
        "sigmoid, and this is what it says about the questions the corpus cannot answer, against what the right "
        "chunks score in scope.\n"
    )
    for run in rerankers:
        rights = [run.outcomes[q.id].right.score for q in in_scope if run.outcomes[q.id].right is not None]
        tops = [run.outcomes[q.id].top[0].score for q in in_scope if run.outcomes[q.id].top]
        if not rights:
            continue
        add(
            f"`{name(run.retrieval)}`: the right chunk's relevance is {statistics.median(rights):.2f} at the median "
            f"and {min(rights):.2f} at the lowest over the {len(rights)} questions it reaches; the top hit's is "
            f"{statistics.median(tops):.2f} at the median.\n"
        )
    add("| Question | " + " | ".join(f"`{name(r.retrieval)}` top" for r in rerankers) + " |")
    add("|---|" + "---:|" * len(rerankers))
    for q in oos:
        add(
            f"| {cell(q.text)} | "
            + " | ".join(
                f"{r.outcomes[q.id].top[0].score:.2f} ({short(r.outcomes[q.id].top[0])})"
                if r.outcomes[q.id].top
                else "–"
                for r in rerankers
            )
            + " |"
        )
    add("")
    add(
        f"A floor on `{name(pick.retrieval)}`'s relevance, and what it costs: in-scope answers it would drop from "
        f"the top {K} against unanswerable questions it would silence. The cosine floor of {floor:.2f} silences "
        f"{cosine_silent} of the {len(oos)} and costs no answer.\n"
    )
    add("| Relevance floor | Answers kept in the top " + str(K) + " | Out-of-scope silenced |")
    add("|---:|---:|---:|")
    answered = [q for q in in_scope if pick.rank(q.id) is not None and pick.rank(q.id) <= K]
    for floor_r in RELEVANCE_GRID:
        kept = sum(pick.outcomes[q.id].right.score >= floor_r for q in answered if pick.outcomes[q.id].right)
        silenced = sum(not pick.outcomes[q.id].top or pick.outcomes[q.id].top[0].score < floor_r for q in oos)
        add(f"| {floor_r:.2f} | {kept}/{len(answered)} | {silenced}/{len(oos)} |")
    add("")
    low = [
        q
        for q in answered
        if pick.outcomes[q.id].right and pick.outcomes[q.id].right.score < RELEVANCE_GRID[0]
    ]
    add(
        (
            f"Under {RELEVANCE_GRID[0]:.2f} the right chunk still scores for "
            + ", ".join(f"`{q.id}` ({pick.outcomes[q.id].right.score:.2f})" for q in low)
            + ": a floor there would silence those along with the unanswerable questions. "
            if low
            else ""
        )
        + "No relevance floor is set by default: the retrieval stage's rule stands, a threshold that costs an "
        "answer is a trade the caller makes, with `--min-relevance`, and the table says what each value buys.\n"
    )

    if cmp.expectations:
        add("## 5. Expectations\n")
        add(
            "Written in [`eval/rerank.yaml`](../eval/rerank.yaml) before any reranker ran, for the questions the "
            f"first stage still got wrong or newly wrong. *Held* when the right chunk moved up under "
            f"`{name(pick.retrieval)}` if it was expected to and did not if it was not.\n"
        )
        add("| Query | Expected | Hypothesis | First stage → rerank | Held |")
        add("|---|---|---|---:|---|")
        held_count = 0
        for e in cmp.expectations:
            before, after = first.rank(e.id), pick.rank(e.id)
            held = worse(before, after) == e.moves
            held_count += held
            add(
                f"| `{e.id}` | {'moves up' if e.moves else 'stays'} | {cell(e.hypothesis.strip())} | "
                f"{rank(before)} → {rank(after)} | {'yes' if held else 'no'} |"
            )
        add(f"\n{held_count} of {len(cmp.expectations)} held.\n")

    add(f"## {6 if cmp.expectations else 5}. The pick, and what still fails\n")
    d = DEFAULT_RETRIEVAL
    default_name = "first stage" if d.rerank is None else f"{d.rerank.model} over {d.rerank.candidates}"
    add(
        f"`retrieve` and `search` use `{d.label}`"
        + (
            f"; the benchmark picks `{name(pick.retrieval)}`. **Update `DEFAULT_RETRIEVAL` in "
            "`src/infra_docs_rag/retrieve/retriever.py`.**"
            if default_name != name(pick.retrieval)
            else f", the benchmark's pick: the most right chunks first under {budget} a question, MRR as the "
            "tiebreak (section 3)."
        )
        + (
            f" Against the first stage it answers {pick.hits(1, in_scope) - first.hits(1, in_scope)} more questions "
            f"first and {pick.hits(K, in_scope) - first.hits(K, in_scope)} more in the top {K}, for "
            f"{pick.mrr(in_scope) - first.mrr(in_scope):+.2f} MRR, at {ms(pick.median('ms', in_scope))} a question "
            f"instead of {ms(first.median('ms', in_scope))}."
            if pick is not first
            else ""
        )
    )
    add("")
    depth = pick.retrieval.rerank.candidates if pick.retrieval.rerank else K
    missing = [q for q in in_scope if pick.rank(q.id) is None or pick.rank(q.id) > K]
    unreached = [q for q in missing if first.rank(q.id) is None or first.rank(q.id) > depth]
    add(
        f"Still outside the top {K} under `{name(pick.retrieval)}`: "
        + (
            ", ".join(
                f"`{q.id}` ({q.kind}, first stage {rank(first.rank(q.id))}, rerank {rank(pick.rank(q.id))})"
                for q in missing
            )
            if missing
            else "nothing"
        )
        + ". "
        + (
            f"{len(unreached)} of them the first stage never hands the reranker: its candidates stop at {depth}, "
            "and the recall ceiling is the first stage's, not the reranker's. "
            if unreached
            else ""
        )
        + "What carries over: the reranked top "
        f"{K} is what grounded generation reads, and its relevance is a second signal for saying nothing.\n"
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out).rstrip() + "\n")


def parameters(cmp: RerankComparison, run: Run) -> str:
    """`22M`, from the reranker the comparison loaded."""
    value = cmp.parameters.get(run.reranker.name, 0) if run.reranker else 0
    return f"{value / 1e6:.0f}M" if value else "–"
