"""`reports/embeddings.md`: the evidence for the embedding stage, generated from an evaluation."""

import re
import statistics
import textwrap
from pathlib import Path

from ..ingest.report import cell, excerpt
from .embedders import MODELS
from .evaluate import KINDS, Evaluation, Probe
from .index import Hit, Manifest

# Why each kind of query behaves the way it does; true whatever the scores come out as.
WHY = {
    "paraphrase": (
        "Different words, same meaning. This is what dense vectors are for: the model learned that the "
        "phrasings are used the same way, so they land close together on its map."
    ),
    "identifier": (
        "An identifier can only match through its word pieces. When the section that defines it is short "
        "and repeats it, those pieces line up with the query and the right section wins. When the key "
        "appears once in a long section, or past the model's token limit, the chunk's vector carries "
        "little or nothing of it. Keyword search keeps an exact match either way, which is what hybrid "
        "search adds later."
    ),
    "metadata": (
        "The answer depends on something the chunk text does not contain: a product named only in the "
        "document title, or a page number kept in the page spans. No embedding of the text can see it; a "
        "metadata filter, or the title prepended to each chunk, can."
    ),
}


def ordinal(n: int) -> str:
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def signed(value: float) -> str:
    return f"{value:+.2f}".replace("-", "−")


def megabytes(size: float) -> str:
    return f"{size / 1e6:.1f} MB"


def block(text: str, language: str = "text") -> str:
    """A fenced code block whose fence outlasts any run of backticks inside the text."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}{language}\n{text}\n{fence}\n"


def format_hits(hits: list[Hit], snippet: int = 150) -> str:
    lines: list[str] = []
    for hit in hits:
        body = hit.chunk.text.removeprefix(hit.chunk.section).strip()
        lines += [f"{hit.rank}. {hit.score:.3f}  {hit.chunk.citation()}", f"   {hit.chunk.source_uri}"]
        lines += [f"   {excerpt(body, snippet)}", ""]
    return "\n".join(lines).rstrip()


def format_search(manifest: Manifest, hits: list[Hit], snippet: int = 150) -> str:
    """What `infra-docs-rag search` prints."""
    header = f"{manifest.model_id} · {manifest.chunks} chunks · cosine similarity"
    return header + "\n\n" + format_hits(hits, snippet)


def verdict(p: Probe, q: int) -> str:
    """One model's result for query q, in words."""
    scores = p.scores[q]
    right, wrong = p.best_right(q), p.best_wrong(q)
    if p.rank(q) == 1:
        return (
            f"`{p.model}` put it first ({scores[right]:.2f} against {scores[wrong]:.2f} "
            f"for `{p.chunks[wrong].section}`)"
        )
    top = p.order(q)[0]
    return (
        f"`{p.model}` put it {ordinal(p.rank(q))}, behind `{p.chunks[top].section}` "
        f"({scores[top]:.2f} against {scores[right]:.2f})"
    )


def write_report(ev: Evaluation, output: Path) -> None:
    queries = ev.query_set.queries
    n = len(queries)
    probes, comparisons = ev.probes, ev.comparisons
    default = probes[ev.default_model]
    chunks = ev.stats.chunks

    out: list[str] = []
    add = out.append
    add("# Embeddings report\n")
    add(
        "Generated by `uv run infra-docs-rag evaluate` from `data/processed/documents.jsonl` (ingest version "
        f"`{ev.ingest_version}`) and the labelled queries in [`eval/queries.yaml`](../eval/queries.yaml). "
        f"Timings are from one run on {ev.machine}.\n"
    )

    add("## Summary\n")
    add("| | |\n|---|---|")
    s = ev.stats
    add(
        f"| Chunks | {s.chunks} sections from {s.documents} documents, one chunk per section with its "
        "heading; real chunking is the next stage |"
    )
    skipped = f"{s.empty_sections} headings with nothing under them"
    if s.without_sections:
        skipped += (
            "; " + ", ".join(f"`{x}`" for x in s.without_sections) + " (no headings, so no sections yet)"
        )
    add(f"| Skipped | {skipped} |")
    add(
        "| Models | "
        + " · ".join(f"`{name}` ({c.manifest.dimensions} dimensions)" for name, c in comparisons.items())
        + " |"
    )
    add("| Metric | Cosine similarity: vectors are stored at length 1, so the dot product is the cosine |")
    kinds = {kind: sum(q.kind == kind for q in queries) for kind in KINDS}
    add(f"| Queries | {n}: " + " · ".join(f"{count} {kind}" for kind, count in kinds.items()) + " |")
    for name, c in comparisons.items():
        add(
            f"| `{name}` | Right section first for {c.hits(1)}/{n} queries, in the top 5 for "
            f"{c.hits(5)}/{n}, MRR {c.mrr:.2f} |"
        )
    add("")

    # 1. Probe
    probe_size = len(default.chunks)
    right_count = len(set().union(*default.right))
    add(f"## 1. Probe: {n} queries against {probe_size} chunks\n")
    add(
        f"Every query is scored against a set small enough to read in full: the {right_count} sections that "
        f"answer one of the queries, plus {probe_size - right_count} decoys picked to look like an answer "
        "without being one. Each cell shows where the best right section lands among the "
        f"{probe_size} (1st is the top) and its margin: its score minus the best wrong chunk's. Each "
        "hypothesis in `eval/queries.yaml` was written before its query was scored.\n"
    )
    add("| Query | Kind | Answered by | " + " | ".join(f"`{name}`" for name in probes) + " |")
    add("|---|---|---|" + "---|" * len(probes))
    for q, query in enumerate(queries):
        answers = [default.chunks[i].section for i in sorted(default.right[q])]
        answered = f"`{cell(answers[0])}`" + (f" and {len(answers) - 1} more" if len(answers) > 1 else "")
        cells = [f"{ordinal(p.rank(q))} ({signed(p.margin(q))})" for p in probes.values()]
        add(f"| {cell(query.text)} | {query.kind} | {answered} | " + " | ".join(cells) + " |")
    add("")

    def misses(q: int) -> int:
        return sum(p.rank(q) > 1 for p in probes.values())

    def mean_margin(q: int) -> float:
        return statistics.fmean(p.margin(q) for p in probes.values())

    picks = {
        "Where embeddings work": sorted(range(n), key=lambda q: (misses(q), -mean_margin(q)))[:3],
        "Where they fail": sorted(range(n), key=lambda q: (-misses(q), mean_margin(q)))[:3],
    }
    for title, chosen in picks.items():
        add(f"### {title}\n")
        for q in chosen:
            query = queries[q]
            add(f'**"{query.text}"** ({query.kind})\n')
            add(f"- Hypothesis: {query.hypothesis}")
            add("- Result: " + "; ".join(verdict(p, q) for p in probes.values()) + ".\n")

    add("### What the probe shows\n")
    for kind in KINDS:
        ids = [q for q, query in enumerate(queries) if query.kind == kind]
        if not ids:
            continue
        firsts = ", ".join(f"`{name}` {sum(p.rank(q) == 1 for q in ids)}" for name, p in probes.items())
        add(f"- **{kind.capitalize()}**, right section first out of {len(ids)}: {firsts}. {WHY[kind]}")
    add("")

    add(f"<details><summary>Every score in the probe, <code>{ev.default_model}</code></summary>\n")
    add(
        "Rows are the probe chunks, columns the queries. Bold marks a right section, ▲ the top score in each column.\n"
    )
    add("| Chunk | " + " | ".join(f"`{query.id}`" for query in queries) + " |")
    add("|---|" + "---:|" * n)
    tops = [default.order(q)[0] for q in range(n)]
    for i, chunk in enumerate(default.chunks):
        values = []
        for q in range(n):
            value = f"{default.scores[q][i]:.2f}"
            if i in default.right[q]:
                value = f"**{value}**"
            values.append(value + (" ▲" if tops[q] == i else ""))
        add(f"| `{chunk.source_id}` › {cell(chunk.section)} | " + " | ".join(values) + " |")
    add("\n</details>\n")

    # 2. Search
    own = comparisons[ev.default_model]
    add("## 2. Search\n")
    add(
        '`uv run infra-docs-rag search "<query>"` embeds the query with the index\'s own model, scores every '
        "chunk and prints the top k with where each one came from. One query of each kind, against the "
        f"`{ev.default_model}` index:\n"
    )
    for query, hits in ev.searches:
        q = queries.index(query)
        add(block(f'$ uv run infra-docs-rag search "{query.text}"\n{format_search(own.manifest, hits, 110)}'))
        add(f"The right section ranks {ordinal(own.ranks[q])} of {chunks}.\n")

    # 3. Comparison
    add("## 3. Model comparison\n")
    add(
        f"The same {n} queries against all {chunks} chunks in each model's index. *First* and *top 5* count "
        "the queries whose right section ranks there; MRR (mean reciprocal rank) averages 1 / rank of the "
        "first right section, so 1.0 means first every time. *Build* is embedding every chunk; *query* is "
        f"embedding one query, scoring every chunk and sorting, the median of {n} runs after a warm-up.\n"
    )
    add(
        "| Model | Dimensions | Parameters | Reads up to | Chunks cut off | Build | Query | Index size | First | Top 5 | MRR |"
    )
    add("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for name, c in comparisons.items():
        m = c.manifest
        add(
            f"| `{name}` | {m.dimensions} | {c.parameters / 1e6:.1f}M | {m.max_tokens} tokens | {m.truncated} "
            f"| {m.build_seconds:.1f} s | {statistics.median(c.latency_ms):.0f} ms | {megabytes(c.index_bytes)} "
            f"| {c.hits(1)}/{n} | {c.hits(5)}/{n} | {c.mrr:.2f} |"
        )
    add("")
    add("Rank of the first right section, per query:\n")
    add("| Query | Kind | " + " | ".join(f"`{name}`" for name in comparisons) + " |")
    add("|---|---|" + "---:|" * len(comparisons))
    for q, query in enumerate(queries):
        add(
            f"| `{query.id}` | {query.kind} | "
            + " | ".join(str(c.ranks[q]) for c in comparisons.values())
            + " |"
        )
    add("")
    add("In the top 5, by kind:\n")
    add("| Kind | " + " | ".join(f"`{name}`" for name in comparisons) + " |")
    add("|---|" + "---:|" * len(comparisons))
    for kind in KINDS:
        ids = [q for q, query in enumerate(queries) if query.kind == kind]
        if ids:
            add(
                f"| {kind} | "
                + " | ".join(f"{c.hits(5, ids)}/{len(ids)}" for c in comparisons.values())
                + " |"
            )
    add("")

    add("### What each model costs to run\n")
    add(
        "Every model here runs locally on the CPU: no API key, no per-token bill, and no text leaves the "
        "machine. The price is a one-time download, memory for the weights, and CPU time for every chunk and "
        "query.\n"
    )
    for name, c in comparisons.items():
        m = c.manifest
        million = 1e6 * m.dimensions * 4
        hours = m.build_seconds / m.chunks * 1e6 / 3600
        add(
            f"- **`{name}`** (`{m.model_id}`): {MODELS[name].note} Weights: about "
            f"{megabytes(c.parameters * 4)}. At a million chunks the vectors alone take {million / 1e9:.1f} GB, "
            f"and re-embedding them at this machine's rate would take about {hours:.0f} hours."
        )
    add(
        "\nThat last number is the cost of changing models later: every stored vector belongs to one "
        "model's map, so a new model means re-embedding the whole corpus and rebuilding the index before "
        "the first query.\n"
    )

    # 4. Mixed maps
    mixed = ev.mixed
    if mixed:
        index_own = comparisons[mixed.index_model]
        dims = index_own.manifest.dimensions
        add("## 4. Mixed maps\n")
        add(
            f"`{mixed.index_model}` and `{mixed.query_model}` both turn text into {dims} numbers, so nothing in "
            "the arithmetic stops a program from comparing their vectors. `search` reads the index's "
            "manifest first and refuses:\n"
        )
        add(block(textwrap.fill(f"error: {mixed.refusal}", 100)))
        add(
            f"With the check bypassed, ranking the `{mixed.index_model}` index against `{mixed.query_model}` "
            f"query vectors puts the right section in the top 5 for {sum(r <= 5 for r in mixed.ranks)}/{n} "
            f"queries, against {index_own.hits(5)}/{n} with its own model. Rank of the right section among "
            f"{chunks} chunks:\n"
        )
        add(f"| Query | `{mixed.index_model}` queries | `{mixed.query_model}` queries |")
        add("|---|---:|---:|")
        for q, query in enumerate(queries):
            add(f"| `{query.id}` | {index_own.ranks[q]} | {mixed.ranks[q]} |")
        found = [q for q in range(n) if index_own.ranks[q] == 1] or list(range(n))
        worst = max(found, key=lambda q: mixed.ranks[q])
        add(
            f'\n"{queries[worst].text}" is the query that falls furthest: `{mixed.index_model}` puts its right '
            f"section {ordinal(index_own.ranks[worst])} with its own query vector and "
            f"{ordinal(mixed.ranks[worst])} with `{mixed.query_model}`'s. The top 3 with mixed maps:\n"
        )
        add(block(format_hits(mixed.top[worst], 110)))

    add("## Reproduce\n")
    add(
        "```sh\n"
        "uv run infra-docs-rag embed                 # bge-small by default; --model minilm | bge-small | bge-base\n"
        f'uv run infra-docs-rag search "{queries[0].text}"\n'
        "uv run infra-docs-rag evaluate              # rebuilds every model's index and rewrites this report\n"
        "```"
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(re.sub(r"\n{3,}", "\n\n", "\n".join(out)) + "\n")
